### ISSUE TITLE
Some of the latest changes are missing in the released version

### ISSUE THREAD

**Issue by rrudakov** [alexander-yakushev/compliment#86] opened 2022-06-23 20:31 UTC
Hello, I noticed that some commits are missing in version 0.3.13

https://github.com/alexander-yakushev/compliment/compare/0.3.13...master

For example from [this PR](https://github.com/alexander-yakushev/compliment/pull/83), so this functionality actually doesn't work in cider-nrepl and CIDER currently.

See: https://github.com/clojure-emacs/cider/issues/3218

**Comment by vmfhrmfoaj** [comment] 2022-06-26 15:06
Hi @rrudakov 

I tested the your case like this:
```clojure
;; see https://github.com/vmfhrmfoaj/compliment/commit/7369b191b6b5bb1210cb13f72532d8615afddb3d
;; in test/compliment/sources/t_local_bindings.clj
(= (into #{} ["one" "two" "hello" "world"])
   (->> (ctx/parse-context
         '(let [{:bar/keys [one two]
                 :foo/keys [hello world]} m]
            __prefix__))
        (src/candidates "" *ns*)
        (strip-tags)
        (into #{})))
;; => true
```
I think the problem is not related to [compliment](https://github.com/alexander-yakushev/compliment).

Luckily, I hadn't the problem you have. I am using own compliment version to customize some features. because of this I manually installed [cider-nrepl](https://github.com/clojure-emacs/cider-nrepl) to local. so, I think the problem is caused by cider-nrepl package in Clojar.
To confirm this, I removed all files in "/.m2/repository/cider/cider-nrepl" directory.
and I tested what you wrote at https://github.com/clojure-emacs/cider/issues/3218 again.
after installing Clojar version cider-nrepl, I couldn't complete local variables.

If you can manually install [cider-nrepl](https://github.com/clojure-emacs/cider-nrepl) and test again, confirming the problem is easy.
1. clone https://github.com/clojure-emacs/cider-nrepl.git
2. change resources/cider/nrepl/version.edn file to "0.28.5"
3. run `PROJECT_VERSION=0.28.5 make install` on the project root directory.

**Comment by vmfhrmfoaj** [comment] 2022-06-26 15:13
And I found an issue related to the problem in [cider](https://github.com/clojure-emacs/cider).

If you can't complete local variables after disconnecting REPL.
It may be caused by not resetting `cider-completion-last-context` variable.

You can workaround the issue by using following code.
```elisp
(advice-add #'cider-completion-flush-caches :after
            (lambda ()
              "Reset `cider-completion-last-context' after flushing caches."
              (setq cider-completion-last-context nil)))

(add-hook 'cider-mode-hook
          (lambda ()
            (setq cider-completion-last-context nil)))
```

**Comment by rrudakov** [comment] 2022-06-26 15:26
Hi @vmfhrmfoaj, thanks for digging into it, the problem is that compliment jar in clojars doesn't have some of the latest changes. You don't have this problem because you use local modified version of compliment (as you have mentioned), so it probably includes all the changes from master branch.

**Comment by vemv** [comment] 2022-06-27 05:33
@rrudakov's link (https://github.com/alexander-yakushev/compliment/compare/0.3.13...master) is an accurate tldr of the problem - one can see feature commits there.

**Comment by bbatsov** [comment] 2022-07-11 06:50
Hmm, I can't imagine how could this possibly happen. I guess it will be addressed by the next release.

**Comment by bbatsov** [comment] 2022-07-11 08:20
I did a 0.3.14 release today, which hopefully addresses the problem mentioned here.

**Comment by rrudakov** [comment] 2022-07-11 08:23
"Bozhidar Batsov" ***@***.***> writes:

> I did a 0.3.14 release today, which hopefully addresses the problem
> mentioned here.

Thank you!

**Closed** 2022-07-22 07:58 UTC
