### ISSUE TITLE
No completion for locals when hashset literal is used within short lambda syntax

### ISSUE THREAD

**Issue by rrudakov** [alexander-yakushev/compliment#118] opened 2024-03-05 14:02 UTC
### Steps to reproduce

Assume the following code:
```clojure
(let [exclude-values ["one" "two"]
      my-var         (into []
                           (remove #(some #{(:value %)} exclude-values))
                           [{:value "one"}
                            {:value "two"}
                            {:value "three"}])]
  my-va__point__)
```

I expect `my-var` to be among completion candidates, but there are no candidates.

If I remove `(remove #(some #{(:value %)} exclude-values))` everything works fine, so I guess this part causes the problem.

### Relevant nREPL logs

```
(-->
  id                        "571"
  op                        "complete"
  session                   "183d8b71-0c93-4107-b623-a9227633cad5"
  time-stamp                "2024-03-05 14:57:02.727265000"
  context                   "(let [exclude-values [\"one\" \"two\"]
      my-var         (into []
                           (remove #(some #{(:value %)} exclude-values))
                           [{:value \"one\"}
                            {:value \"two\"}
                            {:value \"three\"}])]
  __prefix__)
"
  enhanced-cljs-completion? "t"
  ns                        #("app.scheduler.jobs.suggestions.blacklist-sites" 0 46 (face font-lock-type-face cider-block-dynamic-font-lock t cider-locals nil fontified t))
  prefix                    "my-va"
)
(<--
  id          "571"
  session     "183d8b71-0c93-4107-b623-a9227633cad5"
  time-stamp  "2024-03-05 14:57:02.737120000"
  completions nil
  status      ("done")
)
```

**Comment by alexander-yakushev** [comment] 2024-03-07 10:12
Pushed the fix for this in `0.5.2`. @vemv, could you include it into the rolling cider-nrepl, please?

**Comment by vemv** [comment] 2024-03-07 10:29
Sure!

Looks like the changelog needs a tweak btw (0.5.2 not visible)

**Comment by vemv** [comment] 2024-03-10 20:30
(Done! https://github.com/clojure-emacs/cider/blob/c4fa1a84a3b3d03ef5f61cc5d33ff4e91b9a1dce/CHANGELOG.md?plain=1#L19-L22 )

**Comment by alexander-yakushev** [comment] 2024-03-11 08:24
I can confirm that the issue is fixed in the latest CIDER, @rrudakov please check.

**Comment by rrudakov** [comment] 2024-03-11 08:36
Oleksandr Yakushev ***@***.***> writes:

> I can confirm that the issue is fixed in the latest CIDER, @rrudakov 
> please check.

Yes, the problem is fixed. Thanks a lot! The issue can be closed.
--
Best regards, Roman

**Closed** 2024-03-11 08:40 UTC
Labels: bug
